version: '3.9'
services:
    smart-git:
        image: 'wjqserver/smart-git:latest'
        restart: always
        volumes:
            - './smart-git/log/run:/data/smart-git/log'
            - './smart-git/config:/data/smart-git/config'
            - './smart-git/repos:/data/smart-git/repos'
            - './smart-git/db:/data/smart-git/db'
        ports:
            - '8080:8080'
